#!/bin/bash

CONTEXT=`docker context inspect --format="{{.Name}}"`

echo "Context is ${CONTEXT}"

docker buildx create --use ${CONTEXT}

# Install QEmu emulators
docker run -it --rm --privileged tonistiigi/binfmt --install all